/** Spatial compose → PDL for Airbnb-lite PlaygroundCompose. */

const DEFAULTS = {
  AbnButton: (n) => `AbnButton(label: "Button ${n}", tone: .primary, size: .sm)`,
  AbnChip: (n) => `AbnChip(title: "Chip ${n}", state: .idle)`,
  AbnField: (n) =>
    `AbnField(label: "Field ${n}", value: "", helper: "Tap to edit in PDL")`,
};

/**
 * @param {Array<{ kind: keyof typeof DEFAULTS; id: string }>} items
 */
export function generateComposePdl(items) {
  const lets =
    items.length === 0
      ? ""
      : "\n" +
        items
          .map((it, i) => {
            const call = DEFAULTS[it.kind](i + 1);
            return `  let ${it.id} = ${call}`;
          })
          .join("\n\n") +
        "\n";
  const childList = items.map((it) => it.id).join(", ");
  return `// PlaygroundCompose — spatial compose output (Phase P2). Regenerated by the Playground UI.

component PlaygroundCompose() layout {
  direction = .column
  align = .start
  justify = .start
  wrap = .nowrap
  gap = abn.space.md
  padding = EdgeInsets(x: abn.space.lg, y: abn.space.lg)
  background = abn.color.canvas
  width = .fill
  height = .hug
${lets}
  children = [${childList}]
}
`;
}

/**
 * @param {string} kind
 * @param {number} seq
 */
export function nextComposeItem(kind, seq) {
  return { kind, id: `C${seq}` };
}

export const COMPOSE_KINDS = Object.keys(DEFAULTS);
