#!/usr/bin/env node
/**
 * Generate VitePress reference pages from lock files:
 *   shared/frame-props.json              → folded into website/src/generated/objects.md (Frames)
 *   shared/diagnostics.json              → website/src/generated/diagnostics.md
 *   shared/keywords.json                 → appended to website/src/generated/diagnostics.md
 *   shared/language-objects.json         → website/src/generated/objects.md
 *   shared/schema/*.json                 → website/src/generated/json-ir.md
 *   grammar/pdl.ebnf                     → website/src/generated/grammar.md (unpublished wrap)
 *   test-fixtures/pdl/errors/** + tests/ → website/src/generated/error-fixtures.md
 *
 * Edit grammar/pdl.ebnf by hand. This script does not overwrite it.
 */
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT_DIR = join(ROOT, "website", "src", "generated");
const REPO_BLOB = "https://github.com/VeryTinyMachines/pdl/blob/main";

const GENERATED_BANNER = `<!-- Generated by scripts/gen-docs.mjs — do not edit. -->\n`;

function loadJson(rel) {
  return JSON.parse(readFileSync(join(ROOT, rel), "utf8"));
}

function escapeCell(s) {
  return String(s ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ");
}

function objectSlug(name) {
  return String(name).toLowerCase().replace(/[^a-z0-9]+/g, "");
}

function frameSlug(ctor) {
  return ctor === "Icon" || ctor === "Media" ? `${objectSlug(ctor)}-frame` : objectSlug(ctor);
}

function buildObjectCatalog(objects) {
  const types = new Map();
  const frames = new Map();
  const frameCtors = new Map();
  const ctors = new Map();
  const typeCase = new Map();
  const caseOwners = new Map();
  const ci = new Map();

  const addType = (name, slug) => {
    if (!name || types.has(name)) return;
    types.set(name, slug);
    const lower = name.toLowerCase();
    if (!ci.has(lower)) ci.set(lower, []);
    ci.get(lower).push(slug);
  };
  const addCases = (typeName, slug, cases) => {
    for (const raw of cases ?? []) {
      const cse = typeof raw === "string" ? raw : raw.case;
      if (!cse) continue;
      typeCase.set(`${typeName.toLowerCase()}.${cse}`, slug);
      if (!caseOwners.has(cse)) caseOwners.set(cse, new Set());
      caseOwners.get(cse).add(slug);
    }
  };

  for (const t of objects.tokenTypes ?? []) addType(t.name, objectSlug(t.name));
  for (const e of objects.enums ?? []) {
    addType(e.name, objectSlug(e.name));
    addCases(e.name, objectSlug(e.name), e.cases);
  }
  for (const e of objects.preludeEnums ?? []) {
    addType(e.name, objectSlug(e.name));
    addCases(e.name, objectSlug(e.name), e.cases);
  }
  for (const t of objects.paramScalars ?? []) addType(t.name, objectSlug(t.name));
  for (const p of objects.hostProtocols ?? []) addType(p.name, objectSlug(p.name));
  addType("theme", "theme");
  addType("Theme", "theme");
  addType("typeStyle", "typestyle");
  addType("let", "let");
  addType("Let", "let");
  addType("parameters", "parameters");
  addType("if", "conditionals");
  addType("else", "conditionals");
  addType("null", "null");
  addType("self", "self");
  addType("ForEach", "foreach");
  addType("import", "files");
  addType("fixtures", "fixtures");
  addType("usage", "usage");
  addType("Usage", "usage");
  addType("extend", "extend");
  addType("Extend", "extend");
  addType("Rule", "rule");
  addType("rules", "rule");

  for (const k of objects.frameKinds ?? []) {
    const slug = frameSlug(k.ctor);
    frameCtors.set(k.ctor, slug);
    frames.set(k.name, slug);
    if (!types.has(k.ctor)) frames.set(k.ctor, slug);
  }

  for (const c of objects.constructors ?? []) {
    if (c.kind === "frame") continue;
    if (types.has(c.name)) ctors.set(c.name, types.get(c.name));
    else ctors.set(c.name, objectSlug(c.name));
  }

  frames.set("children", "children");
  ctors.set("typeStyle", "typestyle");
  ctors.set("ForEach", "foreach");
  ctors.set("import", "files");
  ctors.set("variant", "variants");
  ctors.set("enum", "variants");
  ctors.set("usage", "usage");
  ctors.set("extend", "extend");
  ctors.set("Rule", "rule");
  ctors.set("rules", "rule");
  ctors.set("Spacer", "spacer");
  ctors.set("Corner", "corner");
  ctors.set("MediaLayer", "medialayer");
  ctors.set("IconRef", "iconref");

  const uniqueCases = new Map();
  for (const [cse, owners] of caseOwners) {
    if (owners.size === 1) uniqueCases.set(cse, [...owners][0]);
  }

  return { types, frames, frameCtors, ctors, typeCase, uniqueCases, ci };
}

function lookupName(name, catalog) {
  if (!name || !catalog) return null;
  if (catalog.frames.has(name)) return catalog.frames.get(name);
  if (catalog.types.has(name)) return catalog.types.get(name);
  if (catalog.ctors.has(name)) return catalog.ctors.get(name);
  const hits = catalog.ci.get(name.toLowerCase());
  if (hits?.length === 1) return hits[0];
  return null;
}

function ctorSlug(name, catalog) {
  return catalog.frameCtors.get(name) ?? catalog.ctors.get(name) ?? catalog.types.get(name) ?? null;
}

function mdObj(label, slug) {
  return `[\`${label}\`](#${slug})`;
}

function linkCodeInner(inner, catalog, self) {
  const dotted = inner.match(/^([A-Za-z][A-Za-z0-9]*)\.([A-Za-z][A-Za-z0-9]*)$/);
  if (dotted) {
    const slug = catalog.typeCase.get(`${dotted[1].toLowerCase()}.${dotted[2]}`) ?? lookupName(dotted[1], catalog);
    if (slug && slug !== self) return mdObj(inner, slug);
  }
  const call = inner.match(/^([A-Za-z][A-Za-z0-9]*)\(\s*(?:…|\.\.\.)?\s*\)$/);
  if (call) {
    const slug = ctorSlug(call[1], catalog);
    if (slug && slug !== self) return mdObj(inner, slug);
  }
  const cse = inner.match(/^\.([A-Za-z][A-Za-z0-9]*)$/);
  if (cse) {
    const slug = catalog.uniqueCases.get(cse[1]);
    if (slug && slug !== self) return mdObj(inner, slug);
  }
  const bare = inner.replace(/\(\s*…\s*\)$/, "");
  const slug = lookupName(bare, catalog);
  if (slug && slug !== self) return mdObj(inner, slug);
  return `\`${inner}\``;
}

function linkProse(text, catalog, self = null) {
  if (!text || !catalog) return text ?? "";
  const holes = [];
  let s = String(text).replace(/\[([^\]]+)\]\([^)]+\)/g, (m) => {
    holes.push(m);
    return `\0${holes.length - 1}\0`;
  });

  s = s.replace(/`([^`]+)`/g, (_, inner) => {
    const linked = linkCodeInner(inner, catalog, self);
    holes.push(linked);
    return `\0${holes.length - 1}\0`;
  });

  s = s.replace(/\b([A-Za-z][A-Za-z0-9]*)\.([A-Za-z][A-Za-z0-9]*)\b/g, (m, type, cse) => {
    const slug = catalog.typeCase.get(`${type.toLowerCase()}.${cse}`) ?? lookupName(type, catalog);
    if (!slug || slug === self) return m;
    const linked = mdObj(m, slug);
    holes.push(linked);
    return `\0${holes.length - 1}\0`;
  });

  s = s.replace(/(?<![`\w])\.([A-Za-z][A-Za-z0-9]*)\b/g, (m, cse) => {
    const slug = catalog.uniqueCases.get(cse);
    if (!slug || slug === self) return m;
    const linked = mdObj(m, slug);
    holes.push(linked);
    return `\0${holes.length - 1}\0`;
  });

  const names = [
    ...catalog.types.keys(),
    ...catalog.frames.keys(),
    ...catalog.ctors.keys(),
  ].filter((n, i, arr) => arr.indexOf(n) === i && /[A-Z]/.test(n)).sort((a, b) => b.length - a.length);
  if (names.length) {
    const re = new RegExp(`(?<!\\[)\\b(${names.map((n) => n.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("|")})\\b(?!\\s*\\()`, "g");
    s = s.replace(re, (m) => {
      const slug = lookupName(m, catalog);
      if (!slug || slug === self) return m;
      const linked = mdObj(m, slug);
      holes.push(linked);
      return `\0${holes.length - 1}\0`;
    });
  }

  return s.replace(/\0(\d+)\0/g, (_, i) => holes[Number(i)]);
}

function linkUsedOn(items, catalog) {
  return (items ?? [])
    .map((u) =>
      String(u)
        .split(".")
        .map((seg) => {
          const slug = lookupName(seg, catalog);
          return slug ? mdObj(seg, slug) : `\`${seg}\``;
        })
        .join("."),
    )
    .join(", ");
}

function formatType(name, typeKey, kind, catalog) {
  if (name === "content") return mdObj("String", "string");
  if (name === "fontFamily") return mdObj("FontFamily", "fontfamily");
  if (name === "style") return mdObj("typeStyle", "typestyle");
  if (kind?.typeName) {
    const slug = lookupName(kind.typeName, catalog);
    return slug ? mdObj(kind.typeName, slug) : `\`${kind.typeName}\``;
  }
  if (Array.isArray(kind?.tokenTypes) && kind.tokenTypes.length) {
    return kind.tokenTypes
      .map((t) => {
        const slug = lookupName(t, catalog);
        return slug ? mdObj(t, slug) : `\`${t}\``;
      })
      .join(", ");
  }
  if (typeKey === "styleRef") return mdObj("typeStyle", "typestyle");
  if (typeKey === "booleanOrCondition") return "`Bool` or condition";
  if (typeKey === "structural") return "`structural`";
  return `\`${escapeCell(typeKey)}\``;
}

function formatValues(kind, catalog) {
  if (!kind) return "—";
  const bits = [];
  if (Array.isArray(kind.cases) && kind.cases.length) {
    const slug = kind.typeName ? lookupName(kind.typeName, catalog) : null;
    bits.push(
      kind.cases.map((c) => (slug ? mdObj(`.${c}`, slug) : `\`.${c}\``)).join(" · "),
    );
  }
  if (kind.range) bits.push(`${kind.range[0]}…${kind.range[1]}`);
  if (kind.nonNegativeNumber) bits.push("≥ 0");
  if (kind.positiveNumber) bits.push("> 0");
  if (kind.tokenTypes?.includes("Sizing") && !kind.cases?.length) {
    bits.push(`${mdObj(".hug", "sizing")} · ${mdObj(".fill", "sizing")} · \`.fixed(n)\``);
  }
  if (!bits.length && Array.isArray(kind.accept)) {
    bits.push(kind.accept.filter((a) => a !== "dotEnum" && a !== "ident" && a !== "call").join(", ") || "—");
  }
  return bits.join(" · ") || "—";
}

function kindProps(kindName, kinds, special) {
  const props = { ...(kinds[kindName]?.props ?? {}) };
  for (const [name, spec] of Object.entries(special ?? {})) {
    if (name === "children") continue;
    if (!spec.kinds?.includes(kindName)) continue;
    if (spec.type) props[name] = { type: spec.type };
    else if (spec.structural) props[name] = { type: "structural" };
  }
  return props;
}

function propRows(props, valueKinds, catalog) {
  const names = Object.keys(props).sort((a, b) => a.localeCompare(b));
  const lines = [
    "| Property | Type | Values |",
    "|----------|------|--------|",
  ];
  for (const name of names) {
    const typeKey = props[name].type;
    const kind = valueKinds[typeKey];
    lines.push(
      `| \`${name}\` | ${formatType(name, typeKey, kind, catalog)} | ${formatValues(kind, catalog)} |`,
    );
  }
  return lines.join("\n");
}

function diagRow(d) {
  const name = d.retired ? "*(retired)*" : `\`${d.name}\``;
  const trigger = escapeCell(d.trigger);
  return `| **${d.code}** | ${name} | ${trigger} |`;
}

function renderDiagnostics(sot, keywords) {
  let body = `${GENERATED_BANNER}
# Diagnostics

When compilation stops, the message includes a **PDL-E** code (error) or **PDL-W** code (warning). Look up the code here. Codes are never reused after retirement.

Catalog: [\`shared/diagnostics.json\`](${REPO_BLOB}/shared/diagnostics.json) (language **${sot.languageVersion}**).

## Errors (PDL-E0xx)

| Code | Name | Trigger |
|------|------|---------|
`;
  for (const d of sot.errors) body += `${diagRow(d)}\n`;

  body += `
## Warnings (PDL-W0xx)

| Code | Name | Trigger |
|------|------|---------|
`;
  for (const d of sot.warnings) body += `${diagRow(d)}\n`;

  body += `
## Message requirements

Every diagnostic **MUST** include:

1. The error or warning code (e.g. \`PDL-E007\`).
2. The source file path and line number (and column where determinable).
3. A human-readable message describing what was found and what was expected.
4. For errors referencing another location (e.g. \`PDL-E003\` duplicate), the location of the first occurrence.
`;
  return body + renderKeywords(keywords);
}

function renderKeywords(sot) {
  let body = `
## Keywords

Words you cannot use as your own names (**PDL-E018**). You do not need to memorize this while learning; the compiler will say so.

Catalog: [\`shared/keywords.json\`](${REPO_BLOB}/shared/keywords.json) (language **${sot.languageVersion}**).

`;
  for (const group of sot.groups) {
    body += `### ${group.title}\n\n`;
    if (group.note) body += `${group.note}\n\n`;
    body += "| Word | Note |\n|------|------|\n";
    for (const w of group.words) {
      body += `| \`${w.word}\` | ${escapeCell(w.note ?? "—")} |\n`;
    }
    body += "\n";
  }
  return body;
}

function schemaFieldTable(schema) {
  const props = schema.properties ?? {};
  const required = new Set(schema.required ?? []);
  const lines = [
    "| Field | Required | Notes |",
    "|-------|----------|-------|",
  ];
  for (const [name, spec] of Object.entries(props)) {
    const req = required.has(name) ? "yes" : "no";
    const bits = [];
    if (spec.const !== undefined) bits.push(`const \`${JSON.stringify(spec.const).replace(/"/g, "")}\``);
    if (spec.type) bits.push(Array.isArray(spec.type) ? spec.type.join(" \\| ") : spec.type);
    if (spec.description) bits.push(spec.description);
    if (spec.additionalProperties) bits.push("map");
    lines.push(`| \`${name}\` | ${req} | ${bits.join(" · ") || "—"} |`);
  }
  return lines.join("\n");
}

function renderJsonIr() {
  const bake = loadJson("shared/schema/baked-design.json");
  const cat = loadJson("shared/schema/component-catalogue.json");
  const resolved = loadJson("shared/schema/resolved-component.json");
  const pack = loadJson("shared/schema/injection-pack.json");
  return `${GENERATED_BANNER}
# Bake and catalogue IR

Hosts and emitters consume JSON, not \`.pdl\`. Nested frame and component-row shapes live in these schema files.

| Artefact | Discriminant | Schema file | Role |
|----------|--------------|-------------|------|
| **Bake** | \`schemaKind: "bakedDesign"\` | [\`shared/schema/baked-design.json\`](${REPO_BLOB}/shared/schema/baked-design.json) | Literal trees for drawing (HTML, future native) |
| **Catalogue** | \`kind: "componentCatalogue"\` | [\`shared/schema/component-catalogue.json\`](${REPO_BLOB}/shared/schema/component-catalogue.json) | Token graph + default/variant trees for codegen |
| **Resolved slice** | \`schemaKind: "resolvedComponent"\` | [\`shared/schema/resolved-component.json\`](${REPO_BLOB}/shared/schema/resolved-component.json) | One component + trimmed \`system\` |
| **Injection pack** | (input JSON) | [\`shared/schema/injection-pack.json\`](${REPO_BLOB}/shared/schema/injection-pack.json) | \`pdl bakePack\` / \`validatePack\` — not PDL syntax |

Language \`schemaVersion\` is **\`1.0.0-beta\`**. Regenerated with \`npm run docs:gen\`.

## \`bakedDesign\`

${schemaFieldTable(bake)}

\`components\` values are baked instances: \`name\`, \`rootKind\`, optional \`bakedParams\`, \`root\` (literal frame tree). No \`primitive:\` / \`semantic:\` markers — those belong on the catalogue.

\`npm run bakeSystem\` / \`bakeComponent\` (and Rust \`pdl bake*\`) emit this shape.

## \`componentCatalogue\`

${schemaFieldTable(cat)}

On CLI output with \`omitEmpty\`, empty maps may be **absent**. Treat missing \`primitives\` / \`semantics\` / \`themes\` / \`typeStyles\` / \`variantTypes\` as \`{}\`. Empty arrays under \`samples\` / \`fixtures\` are **preserved**.

\`npm run catalogue\` / \`graphSystem\` emit this shape.

## \`resolvedComponent\`

${schemaFieldTable(resolved)}

\`npm run graphComponent\` emits this shape.

## Injection pack

${schemaFieldTable(pack)}

Not a \`.pdl\` declaration. Pass the JSON to \`pdl bakePack\` / \`validatePack\`.
`;
}

function renderGrammarFromEbnf(ebnfText) {
  return `${GENERATED_BANNER}
# Grammar (EBNF)

Binding surface syntax. Edit [\`grammar/pdl.ebnf\`](${REPO_BLOB}/grammar/pdl.ebnf); this page is an unpublished CI wrap. Fences are untagged: VitePress/Shiki does not ship an ISO EBNF grammar.

\`foreach-chrome\` (\`before\` / \`between\` / \`after\`) is reserved and may be rejected (PDL-E026). Top-level \`interaction\` and layout \`on\` are PDL-E001.

\`\`\`
${ebnfText.trimEnd()}
\`\`\`
`;
}

function walkPdlFiles(dir, acc = []) {
  for (const ent of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, ent.name);
    if (ent.isDirectory()) walkPdlFiles(p, acc);
    else if (ent.name.endsWith(".pdl")) acc.push(p);
  }
  return acc;
}

function firstComment(src) {
  const m = src.match(/^\/\/\s*(.+)$/m);
  return m ? m[1].trim() : "";
}

function slugNote(base) {
  return base
    .replace(/^e\d{3}-/i, "")
    .replace(/\.pdl$/, "")
    .replace(/-/g, " ");
}

function collectObservedFromTests() {
  const dir = join(ROOT, "tests");
  /** @type {Map<string, { code: string, via: string, phase: string }>} */
  const observed = new Map();
  const loadEntries = new Set();

  function record(file, code, via, phase = "load") {
    const base = file.replace(/^.*\//, "");
    loadEntries.add(base);
    const prev = observed.get(base);
    if (!prev) observed.set(base, { code, via, phase });
  }

  for (const name of readdirSync(dir)) {
    if (!name.endsWith(".ts")) continue;
    const src = readFileSync(join(dir, name), "utf8");
    const via = `tests/${name}`;

    for (const m of src.matchAll(/err\("([^"]+\.pdl)"\)/g)) loadEntries.add(m[1].replace(/^.*\//, ""));
    for (const m of src.matchAll(/fx\("errors\/([^"]+\.pdl)"\)/g)) loadEntries.add(m[1].replace(/^.*\//, ""));
    for (const m of src.matchAll(/"errors\/((?:legacy\/)?[^"]+\.pdl)"/g)) {
      loadEntries.add(m[1].replace(/^.*\//, ""));
    }

    for (const m of src.matchAll(/expectLoadFails\(\s*"(PDL-E\d{3})"\s*,\s*"errors\/([^"]+)"/g)) {
      record(m[2], m[1], via);
    }
    for (const m of src.matchAll(/\["([^"]+\.pdl)"\s*,\s*"(PDL-E\d{3})"/g)) {
      record(m[1], m[2], via);
    }
    for (const m of src.matchAll(/loadDesign\(err\("([^"]+\.pdl)"\)\)[\s\S]{0,400}?"(PDL-E\d{3})"/g)) {
      const slice = src.slice(m.index, m.index + m[0].length);
      const phase = /buildComponentCatalogue/.test(slice)
        ? "catalogue"
        : /buildResolvedTokenMap/.test(slice)
          ? "token-map"
          : "load";
      record(m[1], m[2], via, phase);
    }
    for (const m of src.matchAll(/const cases[^=]*=\s*\[([\s\S]*?)\];\s*\n\s*it\.each\(cases\)\("([^"]+)"/g)) {
      const titleCode = m[2].match(/PDL-E\d{3}/);
      if (!titleCode) continue;
      for (const fm of m[1].matchAll(/"([^"]+\.pdl)"/g)) {
        record(fm[1], titleCode[0], via);
      }
    }
    for (const m of src.matchAll(/\(e as PdlError\)\.code\)\.toBe\("(PDL-E\d{3})"\)/g)) {
      const windowStart = Math.max(0, m.index - 500);
      const window = src.slice(windowStart, m.index);
      const files = [...window.matchAll(/[\w./-]*e\d{3}-[\w.-]+\.pdl/g)];
      const last = files.at(-1);
      if (last) record(last[0], m[1], via);
    }
    if (src.includes("e001-import-missing.pdl") && src.includes("ENOENT")) {
      record("e001-import-missing.pdl", "ENOENT", via, "io");
    }
    if (src.includes("valid-duplicate-component-name.pdl") && /load succeeds/.test(src)) {
      record("valid-duplicate-component-name.pdl", "(valid)", via, "load");
    }
  }

  return { observed, loadEntries };
}

function collectImportedByOracles(files) {
  const imported = new Set();
  for (const abs of files) {
    const src = readFileSync(abs, "utf8");
    for (const m of src.matchAll(/^import\s+"([^"]+)"/gm)) {
      const spec = m[1].replace(/^\.\//, "");
      if (spec.startsWith("../")) continue;
      imported.add(spec.replace(/^.*\//, ""));
    }
  }
  return imported;
}

function classifyErrorFixture(rel, src, observed, loadEntries, importedByOracles) {
  const base = rel.split("/").pop() ?? rel;
  const hit = observed.get(base);
  if (rel.startsWith("legacy/") || rel.includes("/legacy/")) {
    const digits = base.match(/^e(\d{2,3})/i);
    return {
      kind: "legacy",
      filenameCode: digits ? `PDL-E${digits[1].padStart(3, "0")}` : hit?.code ?? null,
      observedCode: hit?.code ?? null,
      phase: hit?.phase ?? "load",
      via: hit?.via ?? "tests/validateDesign.test.ts",
      note: firstComment(src) || "Pre-renumber / historical oracle.",
    };
  }
  if (base.startsWith("valid-")) {
    return {
      kind: "valid",
      filenameCode: null,
      observedCode: hit?.code ?? "(valid)",
      phase: "load",
      via: hit?.via ?? null,
      note: firstComment(src) || "Must load successfully (negative control).",
    };
  }
  const m = base.match(/^e(\d{3})-/i);
  const filenameCode = m ? `PDL-E${m[1]}` : null;
  if (filenameCode && importedByOracles.has(base) && !loadEntries.has(base)) {
    return {
      kind: "support",
      filenameCode,
      observedCode: null,
      phase: "imported",
      via: null,
      note: firstComment(src) || "Imported by another oracle; not a standalone load entry.",
    };
  }
  if (filenameCode) {
    return {
      kind: "error",
      filenameCode,
      observedCode: hit?.code ?? filenameCode,
      phase: hit?.phase ?? "load",
      via: hit?.via ?? null,
      note: firstComment(src) || slugNote(base),
    };
  }
  return {
    kind: "other",
    filenameCode: null,
    observedCode: hit?.code ?? null,
    phase: hit?.phase ?? "load",
    via: hit?.via ?? null,
    note: firstComment(src) || base,
  };
}

function collectErrorFixtures(observed, loadEntries) {
  const dir = join(ROOT, "test-fixtures/pdl/errors");
  const files = walkPdlFiles(dir).sort((a, b) => a.localeCompare(b));
  const importedByOracles = collectImportedByOracles(files);
  return files.map((abs) => {
    const rel = relative(dir, abs).replaceAll("\\", "/");
    const src = readFileSync(abs, "utf8");
    return {
      rel,
      repoPath: `test-fixtures/pdl/errors/${rel}`,
      ...classifyErrorFixture(rel, src, observed, loadEntries, importedByOracles),
    };
  });
}

function renderErrorFixtures(rows, diagnostics) {
  const byCode = new Map((diagnostics.errors ?? []).map((d) => [d.code, d]));
  const errors = rows.filter((r) => r.kind === "error");
  const support = rows.filter((r) => r.kind === "support");
  const legacy = rows.filter((r) => r.kind === "legacy");
  const valid = rows.filter((r) => r.kind === "valid");
  const codesWithFixtures = new Set(errors.map((r) => r.filenameCode));
  const countByCode = new Map();
  const legacyByCode = new Map();
  for (const r of errors) {
    countByCode.set(r.filenameCode, (countByCode.get(r.filenameCode) ?? 0) + 1);
  }
  for (const r of legacy) {
    if (r.filenameCode) legacyByCode.set(r.filenameCode, (legacyByCode.get(r.filenameCode) ?? 0) + 1);
  }
  const missing = (diagnostics.errors ?? []).filter(
    (d) => !d.retired && !codesWithFixtures.has(d.code) && !legacyByCode.has(d.code),
  );
  const mismatches = errors.filter(
    (r) => r.observedCode && r.filenameCode && r.observedCode !== r.filenameCode,
  );

  let body = `${GENERATED_BANNER}
# Error fixtures

Oracle \`.pdl\` files under [\`test-fixtures/pdl/errors/\`](${REPO_BLOB.replace("/blob/main", "/tree/main")}/test-fixtures/pdl/errors). Regenerated with \`npm run docs:gen\` by scanning the directory and joining TypeScript tests under \`tests/\`. Do not maintain this table by hand.

A conforming compiler **MUST** emit the code encoded in the filename (\`e007-…\` → **PDL-E007**), except where a test documents a different code (language evolution — see [Filename vs observed](#filename-vs-observed)). Diagnostic meanings: [Diagnostics](./diagnostics.md).

**${errors.length}** current oracles · **${support.length}** support files · **${legacy.length}** legacy · **${valid.length}** valid controls.

## Coverage by catalog code

Active \`PDL-E\` codes from \`shared/diagnostics.json\`. **Current** counts ignore \`legacy/\` and support files. **Legacy** is extra historical coverage.

| Code | Name | Current | Legacy | Status |
|------|------|---------|--------|--------|
`;

  for (const d of diagnostics.errors ?? []) {
    if (d.retired) continue;
    const n = countByCode.get(d.code) ?? 0;
    const leg = legacyByCode.get(d.code) ?? 0;
    const status = n > 0 ? "covered" : leg > 0 ? "legacy only" : "**gap**";
    const name = d.name ? `\`${d.name}\`` : "—";
    body += `| **${d.code}** | ${name} | ${n} | ${leg} | ${status} |\n`;
  }

  if (missing.length) {
    body += `
## Codes without an oracle

These codes are in the diagnostic catalog but have no \`eNNN-*.pdl\` under \`errors/\` (including \`legacy/\`). That is a **coverage gap**, not a claim that the compiler omits the code.

${missing.map((d) => `- **${d.code}**${d.name ? ` — \`${d.name}\`` : ""} — ${escapeCell(d.trigger)}`).join("\n")}
`;
  }

  if (mismatches.length) {
    body += `
## Filename vs observed

The filename still records the original intent. TypeScript tests assert a **different** code (usually because the language moved: a construct is now a parse error, or a type check was renumbered). Conformance follows the **test**, and treats the filename as historical.

| File | Filename | Observed | Phase | Test |
|------|----------|----------|-------|------|
`;
    for (const r of mismatches) {
      const href = `${REPO_BLOB}/${r.repoPath}`;
      body += `| [\`${r.rel}\`](${href}) | **${r.filenameCode}** | **${r.observedCode}** | ${r.phase} | ${r.via ? `\`${r.via}\`` : "—"} |\n`;
    }
  }

  body += `
## Current oracles

| File | Filename | Observed | Catalog name | Phase | Note |
|------|----------|----------|--------------|-------|------|
`;
  for (const r of errors) {
    const meta = byCode.get(r.filenameCode);
    const name = meta?.retired ? "*(retired)*" : meta?.name ? `\`${meta.name}\`` : "—";
    const href = `${REPO_BLOB}/${r.repoPath}`;
    body += `| [\`${r.rel}\`](${href}) | **${r.filenameCode}** | **${r.observedCode}** | ${name} | ${r.phase} | ${escapeCell(r.note)} |\n`;
  }

  body += `
## Support files

Loaded only as \`import\` targets of another oracle (cycle partners, shared token bases). They are not standalone negative tests.

| File | Note |
|------|------|
`;
  for (const r of support) {
    const href = `${REPO_BLOB}/${r.repoPath}`;
    body += `| [\`${r.rel}\`](${href}) | ${escapeCell(r.note)} |\n`;
  }

  body += `
## Legacy oracles

Kept for historical tests (\`tests/validateDesign.test.ts\`). Prefer the current \`eNNN-\` names for new coverage. Legacy filenames sometimes use two-digit codes (\`e07-\`, \`e10-\`, \`e12-\`).

| File | Observed | Note |
|------|----------|------|
`;
  for (const r of legacy) {
    const href = `${REPO_BLOB}/${r.repoPath}`;
    body += `| [\`${r.rel}\`](${href}) | **${r.observedCode ?? r.filenameCode ?? "—"}** | ${escapeCell(r.note)} |\n`;
  }

  body += `
## Valid controls

These files **must load**. They document merge / last-wins behaviour, not failures.

| File | Note |
|------|------|
`;
  for (const r of valid) {
    const href = `${REPO_BLOB}/${r.repoPath}`;
    body += `| [\`${r.rel}\`](${href}) | ${escapeCell(r.note)} |\n`;
  }

  body += `
## How oracles are named

Current files use \`eNNN-slug.pdl\` (example: [\`e041-unknown-sample-path.pdl\`](${REPO_BLOB}/test-fixtures/pdl/errors/e041-unknown-sample-path.pdl) → **PDL-E041**). The withdrawn layout \`test-fixtures/pdl/09_error_cases/PDL-E007-unresolved-reference.pdl\` is **not** used.

Some diagnostics fire after parse: **catalogue** (\`buildComponentCatalogue\`) or **token-map** (\`buildResolvedTokenMap\`). \`e001-import-missing.pdl\` is an I/O failure (\`ENOENT\`), not a \`PdlError\`.

\`e004-circular-primitives.pdl\` is asserted as **PDL-E004** by tests, while the catalog names **PDL-E013** \`circular-token-reference\`. Treat that as numbering drift in the catalog, not a missing circular-token oracle.
`;
  return body;
}

function assertLanguageObjectsLockstep(objects, frameProps) {
  const byName = new Map((objects.enums ?? []).map((e) => [e.name, e]));
  const missing = [];
  for (const spec of Object.values(frameProps.valueKinds ?? {})) {
    if (!spec.typeName || !Array.isArray(spec.cases)) continue;
    const e = byName.get(spec.typeName);
    if (!e) {
      missing.push(`enum ${spec.typeName} (from frame-props)`);
      continue;
    }
    const have = new Set((e.cases ?? []).map((c) => c.case));
    for (const c of spec.cases) {
      if (!have.has(c)) missing.push(`${spec.typeName}.${c}`);
    }
  }
  if (missing.length) {
    throw new Error(
      `shared/language-objects.json is missing locked meanings:\n  - ${missing.join("\n  - ")}\nAdd the case (and its meaning) before changing frame-props.`,
    );
  }
}

function extractStdlibHostProtocols(text) {
  const result = [];
  const protoRe = /protocol\s+(\w+)\s*\{([\s\S]*?)\n\}/g;
  let m;
  while ((m = protoRe.exec(text))) {
    const inbound = [];
    const verbs = [];
    for (const raw of m[2].split("\n")) {
      const line = raw.replace(/\/\/.*$/, "").trim();
      if (!line || line === "host") continue;
      const verb = line.match(/^(\w+)\s*\(/);
      if (verb) {
        verbs.push(verb[1]);
        continue;
      }
      const inboundM = line.match(/^(\w+)$/);
      if (inboundM) inbound.push(inboundM[1]);
    }
    result.push({ name: m[1], inbound, verbs });
  }
  return result;
}

function assertHostProtocolLockstep(objects, stdlibText) {
  const fromFile = extractStdlibHostProtocols(stdlibText);
  const fromSot = objects.hostProtocols ?? [];
  const missing = [];
  if (fromFile.length !== fromSot.length) {
    missing.push(
      `host protocol count: stdlib has ${fromFile.map((p) => p.name).join(", ") || "(none)"}; language-objects has ${fromSot.map((p) => p.name).join(", ") || "(none)"}`,
    );
  }
  const byName = new Map(fromSot.map((p) => [p.name, p]));
  for (const proto of fromFile) {
    const locked = byName.get(proto.name);
    if (!locked) {
      missing.push(`host protocol ${proto.name}`);
      continue;
    }
    const inbound = new Set((locked.inbound ?? []).map((c) => c.name));
    const verbs = new Set((locked.verbs ?? []).map((v) => v.name));
    for (const name of proto.inbound) {
      if (!inbound.has(name)) missing.push(`${proto.name} inbound ${name}`);
    }
    for (const name of proto.verbs) {
      if (!verbs.has(name)) missing.push(`${proto.name} verb ${name}`);
    }
  }
  if (missing.length) {
    throw new Error(
      `shared/language-objects.json is missing locked host-protocol names:\n  - ${missing.join("\n  - ")}\nKeep lockstep with test-fixtures/pdl/stdlib/host_protocols.pdl.`,
    );
  }
}

function renderPdlExample(code) {
  if (!code) return "";
  return `\`\`\`pdl\n${code}\n\`\`\`\n\n`;
}

function renderPreludeEnum(e, catalog) {
  const slug = objectSlug(e.name);
  let body = `#### \`${e.name}\` {#${slug}}\n\n`;
  body += `${linkProse(e.meaning, catalog, slug)}\n\n`;
  if (e.usedOn?.length) body += `Used on: ${linkUsedOn(e.usedOn, catalog)}.\n\n`;
  body += `| Case | Meaning |\n|------|--------|\n`;
  for (const c of e.cases ?? []) {
    body += `| \`.${c.case}\` | ${linkProse(escapeCell(c.meaning), catalog, slug)} |\n`;
  }
  body += "\n";
  body += renderPdlExample(e.example);
  return body;
}

function renderLockedDetail(heading, slug, intro, obj, catalog, opts = {}) {
  if (!obj) return "";
  let body = `## ${heading} {#${slug}}\n\n`;
  if (intro) body += `${linkProse(intro, catalog, slug)}\n\n`;
  if (obj.meaning) body += `${linkProse(obj.meaning, catalog, slug)}\n\n`;
  if (obj.accept?.length) {
    body += `Accepted syntax:\n\n`;
    for (const a of obj.accept) {
      body += `- \`${a.form}\` — ${linkProse(a.meaning, catalog, slug)}\n`;
    }
    body += "\n";
  }
  if (obj.reject?.length) {
    body += `Rejected:\n\n`;
    for (const r of obj.reject) {
      body += `- \`${r.form}\` — ${linkProse(r.meaning, catalog, slug)}\n`;
    }
    body += "\n";
  }
  if (!opts.skipExample) body += renderPdlExample(obj.example);
  return body;
}

function assertSectionIntros(objects) {
  const required = [
    "declarations",
    "frames",
    "children",
    "spacer",
    "forEach",
    "let",
    "parameters",
    "variants",
    "self",
    "conditionals",
    "conditions",
    "null",
    "tokenTypes",
    "theme",
    "typeStyle",
    "values",
    "layers",
    "assets",
    "enums",
    "eventDirections",
    "emits",
    "protocols",
    "hostPrelude",
    "motion",
    "samples",
    "fixtures",
    "usage",
    "extend",
    "rule",
  ];
  const have = objects.sectionIntros ?? {};
  const missing = required.filter((k) => !have[k]);
  if (missing.length) {
    throw new Error(
      `shared/language-objects.json sectionIntros missing:\n  - ${missing.join("\n  - ")}`,
    );
  }
}

function assertExampleCoverage(objects) {
  const missing = [];
  for (const e of objects.enums ?? []) {
    if (!e.example) missing.push(`enum ${e.name}`);
  }
  for (const e of objects.preludeEnums ?? []) {
    if (!e.example) missing.push(`prelude enum ${e.name}`);
  }
  for (const p of objects.hostProtocols ?? []) {
    if (!p.example) missing.push(`host protocol ${p.name}`);
  }
  for (const k of objects.frameKinds ?? []) {
    if (!k.example) missing.push(`frame ${k.name}`);
  }
  const spacer = (objects.constructors ?? []).find((c) => c.name === "Spacer");
  if (!spacer?.example) missing.push("Spacer example");
  for (const key of [
    "declarationExample",
    "constructorsExample",
    "childrenExample",
    "eventDirectionsExample",
    "emitExample",
    "protocolExample",
    "forEachExample",
    "sampleExample",
  ]) {
    if (!objects[key]) missing.push(key);
  }
  if (!objects.ruleQuery?.example) missing.push("ruleQuery.example");
  if (!objects.rule?.examples?.length) missing.push("rule.examples");
  for (const [i, ex] of (objects.rule?.examples ?? []).entries()) {
    if (!ex.title || !ex.code) missing.push(`rule.examples[${i}]`);
  }
  if (!objects.fixtures?.complexExample) missing.push("fixtures.complexExample");
  for (const key of [
    "theme",
    "lets",
    "parameters",
    "conditionals",
    "typeStyle",
    "null",
    "conditions",
    "syntax",
    "files",
    "arrayChildren",
    "variants",
    "self",
    "motion",
    "fixtures",
    "usage",
    "extend",
    "rule",
  ]) {
    const obj = objects[key];
    if (!obj?.example) missing.push(`${key}.example`);
    if (!Array.isArray(obj?.accept) || !obj.accept.length) missing.push(`${key}.accept`);
  }
  if (missing.length) {
    throw new Error(
      `shared/language-objects.json is missing examples:\n  - ${missing.join("\n  - ")}`,
    );
  }
}

function assertTokenTypeDetail(objects) {
  const missing = [];
  for (const t of objects.tokenTypes ?? []) {
    if (!t.example) missing.push(`${t.name} example`);
    if (!Array.isArray(t.accept) || t.accept.length === 0) {
      missing.push(`${t.name} accept`);
    }
  }
  if (missing.length) {
    throw new Error(
      `shared/language-objects.json token types need the same detail as enums:\n  - ${missing.join("\n  - ")}\nEach type needs accepted syntax and an example.`,
    );
  }
}

function assertDeclarationLockstep(objects, keywords) {
  const group = (keywords.groups ?? []).find((g) => g.id === "declarations");
  if (!group) return;
  const have = new Set((objects.declarations ?? []).map((d) => d.name));
  const missing = (group.words ?? [])
    .map((w) => w.word)
    .filter((word) => !have.has(word));
  if (missing.length) {
    throw new Error(
      `shared/language-objects.json is missing locked declarations:\n  - ${missing.join("\n  - ")}\nEvery keywords.json declarations word needs a meaning here.`,
    );
  }
}

function renderFormTable(rows, columns, catalog) {
  const headers = columns.map((c) => c.header);
  const keys = columns.map((c) => c.key);
  const lines = [
    `| ${headers.join(" | ")} |`,
    `|${headers.map(() => "------").join("|")}|`,
  ];
  for (const row of rows ?? []) {
    lines.push(
      `| ${keys.map((k) => {
        const raw = escapeCell(row[k]);
        if (k === "form" || k === "name") {
          return catalog ? linkCodeInner(String(row[k] ?? ""), catalog, null) : `\`${raw}\``;
        }
        return catalog ? linkProse(raw, catalog) : raw;
      }).join(" | ")} |`,
    );
  }
  return lines.join("\n");
}

function renderCtorGroup(sot, catalog, kind, heading, slug, uniqueHeadings) {
  const rows = (sot.constructors ?? []).filter((c) => c.kind === kind);
  if (!rows.length) return "";
  let body = `## ${heading} {#${slug}}\n\n`;
  const intro = sot.sectionIntros?.[slug] ?? "";
  if (intro) body += `${linkProse(intro, catalog)}\n\n`;
  for (const c of rows) {
    if (uniqueHeadings.has(c.name)) {
      const id = objectSlug(c.name);
      body += `### ${c.name} {#${id}}\n\n${linkProse(c.meaning, catalog, id)}\n\n`;
    }
  }
  const tableRows = rows.filter((c) => !uniqueHeadings.has(c.name) || true);
  body += `| Constructor | Meaning |\n|-------------|--------|\n`;
  for (const c of tableRows) {
    const slugFor = ctorSlug(c.name, catalog);
    const nameCell = slugFor ? mdObj(`${c.name}(…)`, slugFor) : `\`${c.name}(…)\``;
    body += `| ${nameCell} | ${linkProse(escapeCell(c.meaning), catalog)} |\n`;
  }
  body += "\n";
  return body;
}

function renderObjects(sot, frameProps) {
  const catalog = buildObjectCatalog(sot);
  const intro = sot.sectionIntros ?? {};
  const { valueKinds, kinds, childFlexProps, special } = frameProps;
  let body = `${GENERATED_BANNER}
# Language

Every built-in thing you can write in PDL — frames, token types, emits, protocols, samples — with a locked meaning. Look up a type here when you want to know what it is and when to use it. Names you declare with \`variant\` / \`enum\` are yours — see Variants.

Language **${sot.languageVersion}**.

## Declarations {#declarations}

${linkProse(intro.declarations ?? "", catalog)}

`;
  body += `${renderFormTable(sot.declarations, [
    { header: "Name", key: "name" },
    { header: "Form", key: "form" },
    { header: "Meaning", key: "meaning" },
  ], catalog)}\n\n`;
  body += renderPdlExample(sot.declarationExample);

  body += renderLockedDetail("Files and import", "files", intro.files, sot.files, catalog);
  body += renderLockedDetail("Syntax", "syntax", intro.syntax, sot.syntax, catalog);

  body += `## Frames\n\n${linkProse(intro.frames ?? "", catalog)}\n\n`;
  for (const k of sot.frameKinds ?? []) {
    const slug = frameSlug(k.ctor);
    body += `### ${k.ctor} {#${slug}}\n\n`;
    body += `${linkProse(k.meaning, catalog, slug)}\n\n`;
    const props = kindProps(k.name, kinds, special);
    if (Object.keys(props).length) {
      body += `${propRows(props, valueKinds, catalog)}\n\n`;
    }
    body += renderPdlExample(k.example);
  }

  const spacer = (sot.constructors ?? []).find((c) => c.name === "Spacer");
  body += `## Children {#children}\n\n${linkProse(intro.children ?? "", catalog)}\n\n`;
  body += renderPdlExample(sot.childrenExample);
  body += `Child properties sit on the **child** of a ${mdObj("Layout", "layout")} (constructor args or after the \`let\`), not on the parent. A ${mdObj("text", "text")} / ${mdObj("icon", "icon-frame")} / ${mdObj("media", "media-frame")} root does not take these unless a property table says so.\n\n`;
  body += `${propRows(childFlexProps, valueKinds, catalog)}\n\n`;

  if (spacer) {
    body += `## Spacer {#spacer}\n\n`;
    if (intro.spacer) body += `${linkProse(intro.spacer, catalog, "spacer")}\n\n`;
    body += `${linkProse(spacer.meaning, catalog, "spacer")}\n\n`;
    body += renderPdlExample(spacer.example);
  }

  body += renderLockedDetail("Array children", "arraychildren", intro.arrayChildren, sot.arrayChildren, catalog);

  if (sot.forEachForms?.length) {
    body += `## ForEach\n\n${linkProse(intro.forEach ?? "", catalog)}\n\n`;
    body += `${renderFormTable(sot.forEachForms, [
      { header: "Form", key: "form" },
      { header: "Meaning", key: "meaning" },
    ], catalog)}\n\n`;
    body += renderPdlExample(sot.forEachExample);
  }

  body += renderLockedDetail("Let", "let", intro.let, sot.lets, catalog);

  body += renderLockedDetail("Parameters", "parameters", intro.parameters, sot.parameters, catalog);
  for (const t of sot.paramScalars ?? []) {
    const slug = objectSlug(t.name);
    body += `### \`${t.name}\`\n\n${linkProse(t.meaning, catalog, slug)}\n\n`;
  }
  body += `A list of instances is \`[ComponentName]\` (or \`[SomeProtocol]\`).\n\n`;

  body += renderLockedDetail("Variants", "variants", intro.variants, sot.variants, catalog);
  body += renderLockedDetail("self", "self", intro.self, sot.self, catalog);

  body += renderLockedDetail("Conditionals", "conditionals", intro.conditionals, sot.conditionals, catalog);
  body += renderLockedDetail("Conditions", "conditions", intro.conditions, sot.conditions, catalog);
  body += renderLockedDetail("null", "null", intro.null, sot.null, catalog);

  body += `## Token types\n\n${linkProse(intro.tokenTypes ?? "", catalog)}\n\n`;
  for (const t of sot.tokenTypes ?? []) {
    const slug = objectSlug(t.name);
    body += `### \`${t.name}\`\n\n`;
    body += `${linkProse(t.meaning, catalog, slug)}\n\n`;
    const meta = [];
    if (t.category) meta.push(`Category: ${t.category}${t.category === "motion" ? " (draft)" : ""}`);
    if (t.usedOn?.length) meta.push(`Used on: ${linkUsedOn(t.usedOn, catalog)}`);
    if (meta.length) body += `${meta.join(". ")}.\n\n`;
    if (t.accept?.length) {
      body += `Accepted syntax:\n\n`;
      for (const a of t.accept) {
        body += `- \`${a.form}\` — ${linkProse(a.meaning, catalog, slug)}\n`;
      }
      body += "\n";
    }
    if (t.reject?.length) {
      body += `Rejected:\n\n`;
      for (const r of t.reject) {
        body += `- \`${r.form}\` — ${linkProse(r.meaning, catalog, slug)}\n`;
      }
      body += "\n";
    }
    if (t.example) body += `\`\`\`pdl\n${t.example}\n\`\`\`\n\n`;
  }

  body += renderLockedDetail("Theme", "theme", intro.theme, sot.theme, catalog);
  body += renderLockedDetail("typeStyle", "typestyle", intro.typeStyle, sot.typeStyle, catalog);

  body += renderCtorGroup(sot, catalog, "value", "Values", "values", new Set(["Corner"]));
  body += renderCtorGroup(sot, catalog, "layer", "Layers", "layers", new Set(["MediaLayer"]));
  body += renderCtorGroup(sot, catalog, "asset", "Assets", "assets", new Set(["IconRef"]));

  body += `## Enums\n\n${linkProse(intro.enums ?? "", catalog)}\n\n`;
  for (const e of sot.enums ?? []) {
    const slug = objectSlug(e.name);
    body += `### \`${e.name}\`\n\n`;
    body += `${linkProse(e.meaning, catalog, slug)}\n\n`;
    if (e.usedOn?.length) body += `Used on: ${linkUsedOn(e.usedOn, catalog)}.\n\n`;
    body += `| Case | Meaning |\n|------|--------|\n`;
    for (const c of e.cases ?? []) {
      body += `| \`.${c.case}\` | ${linkProse(escapeCell(c.meaning), catalog, slug)} |\n`;
    }
    body += "\n";
    body += renderPdlExample(e.example);
  }

  if (sot.eventDirections?.length) {
    body += `## Messages {#messages}\n\n${linkProse(intro.eventDirections ?? "", catalog)}\n\n`;
    body += `| Surface | Direction | Author wires with | Meaning |\n|---------|-----------|-------------------|--------|\n`;
    for (const d of sot.eventDirections) {
      body += `| \`${escapeCell(d.name)}\` | ${escapeCell(d.direction)} | ${linkProse(escapeCell(d.wire), catalog)} | ${linkProse(escapeCell(d.meaning), catalog)} |\n`;
    }
    body += "\n";
    body += renderPdlExample(sot.eventDirectionsExample);
  }

  if (sot.emitForms?.length) {
    body += `## Emits\n\n${linkProse(intro.emits ?? "", catalog)}\n\n`;
    body += `${renderFormTable(sot.emitForms, [
      { header: "Form", key: "form" },
      { header: "Meaning", key: "meaning" },
    ], catalog)}\n\n`;
    body += renderPdlExample(sot.emitExample);
  }

  if (sot.protocolForms?.length) {
    body += `## Protocols\n\n${linkProse(intro.protocols ?? "", catalog)}\n\n`;
    body += `${renderFormTable(sot.protocolForms, [
      { header: "Form", key: "form" },
      { header: "Meaning", key: "meaning" },
    ], catalog)}\n\n`;
    body += renderPdlExample(sot.protocolExample);
  }

  if (sot.hostProtocols?.length) {
    body += `## Host Protocols {#host-protocols}\n\n${linkProse(intro.hostPrelude ?? "", catalog)}\n\n`;
    for (const p of sot.hostProtocols) {
      const slug = objectSlug(p.name);
      body += `### \`${p.name}\`\n\n${linkProse(p.meaning, catalog, slug)}\n\n`;
      if (p.inbound?.length) {
        body += `Events from the preview:\n\n| Channel | Meaning |\n|---------|--------|\n`;
        for (const c of p.inbound) {
          body += `| \`${c.name}\` | ${linkProse(escapeCell(c.meaning), catalog, slug)} |\n`;
        }
        body += "\n";
      }
      if (p.verbs?.length) {
        body += `Calls you make to the preview:\n\n| Verb | Meaning |\n|------|--------|\n`;
        for (const v of p.verbs) {
          body += `| \`${v.form ?? `${v.name}()`}\` | ${linkProse(escapeCell(v.meaning), catalog, slug)} |\n`;
        }
        body += "\n";
      }
      if (p.injected?.length) {
        body += `State the preview adds to the component:\n\n| Name | Type | Meaning |\n|------|------|--------|\n`;
        for (const i of p.injected) {
          const typeSlug = lookupName(i.type, catalog);
          const typeCell = typeSlug ? mdObj(i.type, typeSlug) : `\`${i.type}\``;
          body += `| \`${i.name}\` | ${typeCell} | ${linkProse(escapeCell(i.meaning), catalog, slug)} |\n`;
        }
        body += "\n";
      }
      const injectedTypes = new Set((p.injected ?? []).map((i) => i.type));
      for (const e of sot.preludeEnums ?? []) {
        if (injectedTypes.has(e.name)) body += renderPreludeEnum(e, catalog);
      }
      body += renderPdlExample(p.example);
    }
  }

  body += renderLockedDetail("Handler motion (draft)", "motion", intro.motion, sot.motion, catalog);

  if (sot.sampleForms?.length) {
    body += `## Samples\n\n${linkProse(intro.samples ?? "", catalog)}\n\n`;
    body += `${renderFormTable(sot.sampleForms, [
      { header: "Form", key: "form" },
      { header: "Meaning", key: "meaning" },
    ], catalog)}\n\n`;
    body += renderPdlExample(sot.sampleExample);
  }

  if (sot.fixtures) {
    const fx = sot.fixtures;
    body += `## Fixtures {#fixtures}\n\n`;
    if (intro.fixtures) body += `${linkProse(intro.fixtures, catalog, "fixtures")}\n\n`;
    if (fx.meaning) body += `${linkProse(fx.meaning, catalog, "fixtures")}\n\n`;
    if (fx.accept?.length) {
      body += `Accepted syntax:\n\n`;
      for (const a of fx.accept) {
        body += `- \`${a.form}\` — ${linkProse(a.meaning, catalog, "fixtures")}\n`;
      }
      body += "\n";
    }
    if (fx.reject?.length) {
      body += `Rejected:\n\n`;
      for (const r of fx.reject) {
        body += `- \`${r.form}\` — ${linkProse(r.meaning, catalog, "fixtures")}\n`;
      }
      body += "\n";
    }
    body += `### Button variants\n\n`;
    body += renderPdlExample(fx.example);
    body += `### A playlist view\n\n`;
    body += renderPdlExample(fx.complexExample);
  }

  body += renderLockedDetail("Usage", "usage", intro.usage, sot.usage, catalog);
  body += renderLockedDetail("Extend", "extend", intro.extend, sot.extend, catalog);
  body += renderLockedDetail("Rule", "rule", intro.rule, sot.rule, catalog, {
    skipExample: Boolean(sot.rule?.examples?.length),
  });
  for (const ex of sot.rule?.examples ?? []) {
    if (!ex.title || !ex.code) continue;
    body += `### ${ex.title}\n\n`;
    body += renderPdlExample(ex.code);
  }

  const rq = sot.ruleQuery;
  if (rq) {
    body += `Strengths are ${mdObj("RuleStrength", "rulestrength")}.\n\n`;
    if (rq.navigators?.length) {
      body += `### Navigators\n\n| Navigator | Meaning |\n|-----------|--------|\n`;
      for (const n of rq.navigators) {
        body += `| \`${n.name}\` | ${linkProse(escapeCell(n.meaning), catalog)} |\n`;
      }
      body += "\n";
    }
    if (rq.filters?.length) {
      body += `### Filters\n\n`;
      body += `${renderFormTable(rq.filters, [
        { header: "Form", key: "form" },
        { header: "Meaning", key: "meaning" },
      ], catalog)}\n\n`;
    }
    if (rq.aggregates?.length) {
      body += `### Aggregates\n\n`;
      body += `${renderFormTable(rq.aggregates, [
        { header: "Form", key: "form" },
        { header: "Meaning", key: "meaning" },
      ], catalog)}\n\n`;
    }
    if (rq.ordering?.length) {
      body += `### Ordering\n\n`;
      body += `${renderFormTable(rq.ordering, [
        { header: "Form", key: "form" },
        { header: "Meaning", key: "meaning" },
      ], catalog)}\n\n`;
    }
  }

  return body;
}

const diagnostics = loadJson("shared/diagnostics.json");
const frameProps = loadJson("shared/frame-props.json");
const languageObjects = loadJson("shared/language-objects.json");
assertLanguageObjectsLockstep(languageObjects, frameProps);
assertTokenTypeDetail(languageObjects);
assertExampleCoverage(languageObjects);
assertSectionIntros(languageObjects);
assertHostProtocolLockstep(
  languageObjects,
  readFileSync(join(ROOT, "test-fixtures/pdl/stdlib/host_protocols.pdl"), "utf8"),
);
assertDeclarationLockstep(languageObjects, loadJson("shared/keywords.json"));
const ebnfText = readFileSync(join(ROOT, "grammar", "pdl.ebnf"), "utf8");
const { observed, loadEntries } = collectObservedFromTests();
const errorRows = collectErrorFixtures(observed, loadEntries);

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(join(OUT_DIR, "objects.md"), renderObjects(languageObjects, frameProps));
writeFileSync(join(OUT_DIR, "diagnostics.md"), renderDiagnostics(diagnostics, loadJson("shared/keywords.json")));
writeFileSync(join(OUT_DIR, "json-ir.md"), renderJsonIr());
writeFileSync(join(OUT_DIR, "error-fixtures.md"), renderErrorFixtures(errorRows, diagnostics));
writeFileSync(join(OUT_DIR, "grammar.md"), renderGrammarFromEbnf(ebnfText));
console.log(`Wrote generated docs → ${OUT_DIR}`);
console.log(`Wrapped grammar/pdl.ebnf (${ebnfText.split("\n").length} lines)`);
console.log(`Indexed ${errorRows.length} error fixtures`);
